#!/bin/bash

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=0xff00ff00
  inactive_color=0x00000000
  whitelist="Microsoft Teams,Microsoft Teams (work or school),Terminal,iTerm2,Ghostty,Alacritty,Kitty,Google Chrome,Safari,Firefox,Brave Browser,Arc"
)

borders "${options[@]}"
